CREATE TABLE classmates (
  classmId INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  age INTEGER NOT NULL,
  adress TEXT NOT NULL
);

-- insert
INSERT INTO classmates VALUES (0001, 'ALEX', '25', 'MOSCOW');
INSERT INTO classmates VALUES (0002, 'JHON', '31','SAINT-PETERSBURG');
INSERT INTO classmates VALUES (0003, 'EKATERINA','19', 'VLADIVOSTOK');
INSERT INTO classmates VALUES (0004, 'VLADIMIR','34', 'MOSCOW');
INSERT INTO classmates VALUES (0005, 'SVETLANA', '26','MOSCOW');
INSERT INTO classmates VALUES (0006, 'IRINA','26', 'VLADIVOSTOK');
INSERT INTO classmates VALUES (0007, 'SEMEN', '27','SAINT-PETERSBURG');
INSERT INTO classmates VALUES (0008, 'YAMADA', '20','SAINT-PETERSBURG');

-- fetch 
SELECT name FROM classmates WHERE adress = 'MOSCOW' AND age  >= 18 AND age < 31;
