CREATE TABLE CLASSMATES (
  classmId INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  age INTEGER NOT NULL,
  adress TEXT NOT NULL
);

-- insert
INSERT INTO CLASSMATES VALUES (0001, 'ALEX', '25', 'MOSCOW');
INSERT INTO CLASSMATES VALUES (0002, 'JHON', '31','SAINT-PETERSBURG');
INSERT INTO CLASSMATES VALUES (0003, 'EKATERINA','19', 'VLADIVOSTOK');
INSERT INTO CLASSMATES VALUES (0004, 'VLADIMIR','34', 'MOSCOW');
INSERT INTO CLASSMATES VALUES (0005, 'SVETLANA', '26','MOSCOW');
INSERT INTO CLASSMATES VALUES (0006, 'IRINA','26', 'VLADIVOSTOK');
INSERT INTO CLASSMATES VALUES (0007, 'SEMEN', '27','SAINT-PETERSBURG');
INSERT INTO CLASSMATES VALUES (0008, 'YAMADA', '20','SAINT-PETERSBURG');

-- fetch 
SELECT name FROM CLASSMATES WHERE adress = 'MOSCOW' and age  > 18 and age < 31;
